# Generated by Django 3.2.8 on 2021-12-01 18:31

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='contact_message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, upload_to='images/')),
                ('img1', models.ImageField(blank=True, upload_to='images/')),
                ('img2', models.ImageField(blank=True, upload_to='images/')),
                ('time', models.DateTimeField(verbose_name=datetime.datetime(2021, 12, 1, 18, 31, 56, 268621, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Quotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('time', models.DateTimeField(verbose_name=datetime.datetime(2021, 12, 1, 18, 31, 56, 268621, tzinfo=utc))),
                ('image', models.ImageField(blank=True, upload_to='images/quotes/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Proj_achievements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('time', models.DateTimeField()),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('pro_video', models.FileField(blank=True, upload_to='videos/project/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('image1', models.ImageField(upload_to='images/')),
                ('body2', models.TextField()),
                ('image2', models.ImageField(upload_to='images/')),
                ('body3', models.TextField()),
                ('image3', models.ImageField(upload_to='images/')),
                ('time', models.DateTimeField(verbose_name=datetime.datetime(2021, 12, 1, 18, 31, 56, 237373, tzinfo=utc))),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'post',
            },
        ),
        migrations.CreateModel(
            name='Legislative_activitie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('time', models.DateTimeField(verbose_name=datetime.datetime(2021, 12, 1, 18, 31, 56, 253005, tzinfo=utc))),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('pro_video', models.FileField(blank=True, upload_to='videos/bill/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Empowerment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('time', models.DateTimeField(verbose_name=datetime.datetime(2021, 12, 1, 18, 31, 56, 268621, tzinfo=utc))),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('video_emp', models.FileField(blank=True, upload_to='Video/empowerment/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('time', models.DateTimeField(verbose_name=datetime.datetime(2021, 12, 1, 18, 31, 56, 253005, tzinfo=utc))),
                ('image', models.ImageField(upload_to='images/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
