# Generated by Django 3.2.8 on 2021-12-03 00:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polweb', '0010_auto_20211202_0553'),
    ]

    operations = [
        migrations.AddField(
            model_name='empowerment',
            name='body1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='empowerment',
            name='body2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='empowerment',
            name='body3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='empowerment',
            name='body4',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='empowerment',
            name='image1',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='empowerment',
            name='image1b',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='empowerment',
            name='image2',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='empowerment',
            name='image2b',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='empowerment',
            name='image3',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='empowerment',
            name='image4',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='legislative_activitie',
            name='body1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='legislative_activitie',
            name='body2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='legislative_activitie',
            name='body3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='legislative_activitie',
            name='body4',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='legislative_activitie',
            name='image1',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='legislative_activitie',
            name='image1b',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='legislative_activitie',
            name='image2',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='legislative_activitie',
            name='image2b',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='legislative_activitie',
            name='image3',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='legislative_activitie',
            name='image4',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='proj_achievements',
            name='body1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='proj_achievements',
            name='body2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='proj_achievements',
            name='body3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='proj_achievements',
            name='body4',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='proj_achievements',
            name='image1',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='proj_achievements',
            name='image1b',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='proj_achievements',
            name='image2',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='proj_achievements',
            name='image2b',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='proj_achievements',
            name='image3',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='proj_achievements',
            name='image4',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='about',
            name='time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 12, 3, 0, 5, 5, 356214, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='empowerment',
            name='time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 12, 3, 0, 5, 5, 371846, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='image',
            name='time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 12, 3, 0, 5, 5, 387472, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='legislative_activitie',
            name='time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 12, 3, 0, 5, 5, 356214, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 12, 3, 0, 5, 5, 340588, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='quotes',
            name='time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 12, 3, 0, 5, 5, 371846, tzinfo=utc)),
        ),
    ]
