# Generated by Django 3.2.8 on 2021-12-03 15:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polweb', '0012_auto_20211203_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='img1',
        ),
        migrations.AlterField(
            model_name='about',
            name='time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 12, 3, 15, 14, 7, 243518, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='empowerment',
            name='time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 12, 3, 15, 14, 7, 274751, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='image',
            name='time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 12, 3, 15, 14, 7, 274751, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='legislative_activitie',
            name='time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 12, 3, 15, 14, 7, 259137, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 12, 3, 15, 14, 7, 227878, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='quotes',
            name='time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 12, 3, 15, 14, 7, 259137, tzinfo=utc)),
        ),
    ]
