# Generated by Django 3.2.8 on 2021-12-03 19:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polweb', '0014_auto_20211203_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='img1',
        ),
        migrations.RemoveField(
            model_name='image',
            name='img2',
        ),
        migrations.AlterField(
            model_name='about',
            name='time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 12, 3, 19, 47, 53, 193371, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='empowerment',
            name='time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 12, 3, 19, 47, 53, 208997, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='image',
            name='time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 12, 3, 19, 47, 53, 231210, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='legislative_activitie',
            name='time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 12, 3, 19, 47, 53, 193371, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 12, 3, 19, 47, 53, 177740, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='quotes',
            name='time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 12, 3, 19, 47, 53, 208997, tzinfo=utc)),
        ),
    ]
