# Generated by Django 3.2.8 on 2021-12-03 19:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polweb', '0015_auto_20211203_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='img1',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='image',
            name='img2',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='about',
            name='time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 12, 3, 19, 48, 52, 669843, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='empowerment',
            name='time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 12, 3, 19, 48, 52, 701101, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='image',
            name='time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 12, 3, 19, 48, 52, 701101, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='legislative_activitie',
            name='time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 12, 3, 19, 48, 52, 685481, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 12, 3, 19, 48, 52, 669843, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='quotes',
            name='time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 12, 3, 19, 48, 52, 685481, tzinfo=utc)),
        ),
    ]
